dist: trusty
sudo: required

services:
  -docker

matrix:
  include:
  - name: Client Web
  
language: node_js
node_js:
  - 'lts/*'

addons:
  apt:
    sources:
      - chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

before-deploy:
  - docker build -t estefaduque-webapp .

deploy:
    skip_cleanup: true
    provider: script
    script: bash ./deploy.sh
    on:
      branch: master
