sudo: required

services:
    -docker
    
matrix:
    include:
    - name: Client Web
    
before_install:
    -docker build -t estefaduque-webapp .

deploy:
    skip_cleanup: true
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master
