sudo: required

services:
    -docker
    
matrix:
    include:
    - name: Client Web
addons:
  chrome: stable

before_install:
  - # start your web application and listen on `localhost`
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    ⋮
    - docker build -t estefaduque-webapp-test -f Dockerfile.test .
  

script: 
    - docker run -e CI=true estefaduque-webapp-test

before-deploy:
    -docker  build -t estefaduque-webapp .

deploy:
    skip_cleanup: true
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master
