sudo: required

services:
    -docker
    
matrix:
    include:
    - name: Client Web

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - docker build -t estefaduque-webapp-test -f Dockerfile.test .

script: 
    - docker run -e CI=true estefaduque-webapp-test

before-deploy:
    -docker  build -t estefaduque-webapp .

deploy:
    skip_cleanup: true
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master
