FROM node:alpine
WORKDIR /usr/src/prueba-aws
COPY package*.json ./
ENV CHROME_BIN=/usr/bin/google-chrome
RUN npm install
# Install Google Chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -y google-chrome-stable
COPY . . 


CMD ["npm", "run", "test","--","--watch=false","--no-progress","--browsers=ChromeHeadlessNoSandbox"]

